apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: search_service_app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: CONFIG_NAME
          value: "docker"
